# Generated by Django 3.2 on 2021-04-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField(unique=True)),
                ('paper_title', models.CharField(max_length=100)),
                ('author_keywords', models.TextField()),
                ('abstract', models.TextField()),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=80)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=20, unique=True)),
                ('countryid', models.IntegerField()),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.IntegerField(unique=True)),
                ('query', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('results', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Searches', to='recsys.user')),
            ],
        ),
    ]
