# Generated by Django 3.2 on 2021-04-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approved',
        ),
    ]
