# Generated by Django 3.2 on 2021-04-20 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recsys', '0002_remove_user_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('passport', models.CharField(max_length=20, unique=True)),
                ('countryid', models.IntegerField()),
                ('username', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='user_search',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Searches', to='recsys.user_detail'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
