# Generated by Django 3.2 on 2021-04-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0003_auto_20210420_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
