# Generated by Django 3.2 on 2021-04-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0005_alter_user_detail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
