# Generated by Django 3.2 on 2021-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0007_auto_20210422_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
