# Generated by Django 3.2 on 2021-04-23 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recsys', '0008_alter_user_detail_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='username',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_search',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
