# Generated by Django 3.2 on 2021-04-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0009_auto_20210423_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_search',
            name='search_id',
        ),
    ]
